name: case_fe
description: Flutter frontend for CASE system

version: 0.0.1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  riverpod: ^2.4.0
  logger: ^2.0.2
  hive: ^2.2.3
  flutter_riverpod: ^2.4.0
  hive_flutter: ^1.1.0
  image_picker: ^1.0.4
  file_picker: ^5.5.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/config/
